<?php

declare(strict_types=1);

namespace Sgso\Ruteo;

use Sgso\Reglas\Permisos;

final class Tabla
{
    /** @return list<Ruta> */
    public static function rutas(): array
    {
        return [
            new Ruta('POST', '/auth/login', null, true, 'auth.login'),
            new Ruta('POST', '/auth/olvide', null, true, 'auth.olvide'),
            new Ruta('POST', '/auth/restablecer', null, true, 'auth.restablecer'),
            new Ruta('POST', '/auth/register', null, false, 'auth.register'),
            new Ruta('GET', '/auth/me', null, false, 'auth.me'),
            new Ruta('GET', '/health', null, true, 'health.mostrar'),

            new Ruta('GET', '/reportes', null, false, 'reportes.listar'),
            new Ruta('POST', '/reportes', Permisos::DOC, false, 'reportes.crear'),
            new Ruta('POST', '/reportes/{id}/enviar', Permisos::DOC, false, 'reportes.enviar'),
            new Ruta('POST', '/reportes/{id}/aprobar', Permisos::REPORTE_APROBAR, false, 'reportes.aprobar'),
            new Ruta('POST', '/reportes/{id}/rechazar', Permisos::REPORTE_APROBAR, false, 'reportes.rechazar'),
            new Ruta('PUT', '/reportes/{id}', Permisos::DOC, false, 'reportes.editar'),
            new Ruta('DELETE', '/reportes/{id}', Permisos::DOC, false, 'reportes.eliminar'),

            new Ruta('GET', '/maquinaria', null, false, 'maquinaria.listar'),
            new Ruta('POST', '/maquinaria', Permisos::GESTION_OBRA, false, 'maquinaria.crear'),
            new Ruta('GET', '/maquinaria/operarios', null, false, 'maquinaria.operarios'),
            new Ruta('GET', '/maquinaria/registro', null, false, 'error.falta.registro'),
            new Ruta('POST', '/maquinaria/registro', null, false, 'error.falta.registro'),
            new Ruta('PUT', '/maquinaria/registro', null, false, 'error.falta.registro'),
            new Ruta('DELETE', '/maquinaria/registro', null, false, 'error.falta.registro'),
            new Ruta('GET', '/maquinaria/falla', null, false, 'error.falta.falla'),
            new Ruta('POST', '/maquinaria/falla', null, false, 'error.falta.falla'),
            new Ruta('PUT', '/maquinaria/falla', null, false, 'error.falta.falla'),
            new Ruta('DELETE', '/maquinaria/falla', null, false, 'error.falta.falla'),
            new Ruta('DELETE', '/maquinaria/registro/{id}', Permisos::DOC, false, 'maquinaria.registro.eliminar'),
            new Ruta('DELETE', '/maquinaria/falla/{id}', Permisos::DOC, false, 'maquinaria.falla.eliminar'),
            new Ruta('GET', '/maquinaria/{id}/registros', null, false, 'maquinaria.registros.listar'),
            new Ruta('POST', '/maquinaria/{id}/registros', Permisos::DOC, false, 'maquinaria.registros.crear'),
            new Ruta('GET', '/maquinaria/{id}/fallas', null, false, 'maquinaria.fallas.listar'),
            new Ruta('POST', '/maquinaria/{id}/fallas', Permisos::DOC, false, 'maquinaria.fallas.crear'),
            new Ruta('DELETE', '/maquinaria/{id}', Permisos::GESTION_OBRA, false, 'maquinaria.eliminar'),

            new Ruta('GET', '/usuarios', Permisos::ADMIN, false, 'usuarios.listar'),
            new Ruta('PUT', '/usuarios/{id}', Permisos::ADMIN, false, 'usuarios.actualizar'),
            new Ruta('GET', '/analisis', null, false, 'analisis.resumen'),
            new Ruta('GET', '/materiales', null, false, 'materiales.listar'),
            new Ruta('POST', '/materiales', Permisos::GESTION_OBRA, false, 'materiales.crear'),

            new Ruta('GET', '/planificacion', null, false, 'error.falta.planificacion'),
            new Ruta('POST', '/planificacion', null, false, 'error.falta.planificacion'),
            new Ruta('PUT', '/planificacion', null, false, 'error.falta.planificacion'),
            new Ruta('DELETE', '/planificacion', null, false, 'error.falta.planificacion'),
            new Ruta('GET', '/planificacion/avance', null, false, 'error.falta.avance'),
            new Ruta('POST', '/planificacion/avance', null, false, 'error.falta.avance'),
            new Ruta('PUT', '/planificacion/avance', null, false, 'error.falta.avance'),
            new Ruta('DELETE', '/planificacion/avance', null, false, 'error.falta.avance'),
            new Ruta('GET', '/planificacion/etapa', null, false, 'error.falta.etapa'),
            new Ruta('POST', '/planificacion/etapa', null, false, 'error.falta.etapa'),
            new Ruta('PUT', '/planificacion/etapa', null, false, 'error.falta.etapa'),
            new Ruta('DELETE', '/planificacion/etapa', null, false, 'error.falta.etapa'),
            new Ruta('GET', '/planificacion/avance/{id}', null, false, 'avance.mostrar'),
            new Ruta('PUT', '/planificacion/avance/{id}', Permisos::AVANCE, false, 'avance.actualizar'),
            new Ruta('DELETE', '/planificacion/avance/{id}', Permisos::AVANCE, false, 'avance.eliminar'),
            new Ruta('PUT', '/planificacion/etapa/{id}', Permisos::GESTION_OBRA, false, 'etapa.actualizar'),
            new Ruta('DELETE', '/planificacion/etapa/{id}', Permisos::GESTION_OBRA, false, 'etapa.eliminar'),
            new Ruta('GET', '/planificacion/{id}/etapas', null, false, 'etapa.listar'),
            new Ruta('POST', '/planificacion/{id}/etapas', Permisos::GESTION_OBRA, false, 'etapa.crear'),
            new Ruta('GET', '/planificacion/{id}/avances/resumen', null, false, 'avance.resumen'),
            new Ruta('GET', '/planificacion/{id}/avances', null, false, 'avance.listar'),
            new Ruta('POST', '/planificacion/{id}/avances', Permisos::AVANCE, false, 'avance.crear'),
            new Ruta('PUT', '/planificacion/{id}', Permisos::GESTION_OBRA, false, 'planificacion.actualizar'),
            new Ruta('DELETE', '/planificacion/{id}', Permisos::GESTION_OBRA, false, 'planificacion.eliminar'),

            new Ruta('DELETE', '/proyectos/asistencia/{id}', Permisos::AVANCE, false, 'asistencia.eliminar'),
            new Ruta('GET', '/proyectos/asistencia', null, false, 'error.falta.asistencia'),
            new Ruta('POST', '/proyectos/asistencia', null, false, 'error.falta.asistencia'),
            new Ruta('PUT', '/proyectos/asistencia', null, false, 'error.falta.asistencia'),
            new Ruta('DELETE', '/proyectos/asistencia', null, false, 'error.falta.asistencia'),
            new Ruta('DELETE', '/proyectos/incidencia/{id}', Permisos::AVANCE, false, 'incidencia.eliminar'),
            new Ruta('GET', '/proyectos/incidencia', null, false, 'error.falta.incidencia'),
            new Ruta('POST', '/proyectos/incidencia', null, false, 'error.falta.incidencia'),
            new Ruta('PUT', '/proyectos/incidencia', null, false, 'error.falta.incidencia'),
            new Ruta('DELETE', '/proyectos/incidencia', null, false, 'error.falta.incidencia'),
            new Ruta('GET', '/proyectos/material', null, false, 'error.falta.asignacion'),
            new Ruta('POST', '/proyectos/material', null, false, 'error.falta.asignacion'),
            new Ruta('PUT', '/proyectos/material', null, false, 'error.falta.asignacion'),
            new Ruta('DELETE', '/proyectos/material', null, false, 'error.falta.asignacion'),
            new Ruta('GET', '/proyectos/material/{id}/consumos', null, false, 'material.consumos.listar'),
            new Ruta('POST', '/proyectos/material/{id}/consumos', Permisos::AVANCE, false, 'material.consumos.crear'),
            new Ruta('DELETE', '/proyectos/material/{id}', Permisos::GESTION_OBRA, false, 'material.asignacion.eliminar'),
            new Ruta('DELETE', '/proyectos/consumo/{id}', Permisos::AVANCE, false, 'material.consumo.eliminar'),
            new Ruta('GET', '/proyectos/consumo', null, false, 'error.falta.consumo'),
            new Ruta('POST', '/proyectos/consumo', null, false, 'error.falta.consumo'),
            new Ruta('PUT', '/proyectos/consumo', null, false, 'error.falta.consumo'),
            new Ruta('DELETE', '/proyectos/consumo', null, false, 'error.falta.consumo'),
            new Ruta('DELETE', '/proyectos/documento/{id}', Permisos::DOC, false, 'documento.eliminar'),
            new Ruta('GET', '/proyectos/documento', null, false, 'error.falta.documento'),
            new Ruta('POST', '/proyectos/documento', null, false, 'error.falta.documento'),
            new Ruta('PUT', '/proyectos/documento', null, false, 'error.falta.documento'),
            new Ruta('DELETE', '/proyectos/documento', null, false, 'error.falta.documento'),
            new Ruta('PUT', '/proyectos/inactividad/{id}', Permisos::DOC, false, 'inactividad.cerrar'),
            new Ruta('GET', '/proyectos/inactividad', null, false, 'error.falta.periodo'),
            new Ruta('POST', '/proyectos/inactividad', null, false, 'error.falta.periodo'),
            new Ruta('PUT', '/proyectos/inactividad', null, false, 'error.falta.periodo'),
            new Ruta('DELETE', '/proyectos/inactividad', null, false, 'error.falta.periodo'),
            new Ruta('DELETE', '/proyectos/inactividad/{id}', Permisos::DOC, false, 'inactividad.eliminar'),
            new Ruta('DELETE', '/proyectos/excedente/{id}', Permisos::DOC, false, 'excedente.eliminar'),
            new Ruta('GET', '/proyectos/excedente', null, false, 'error.falta.item'),
            new Ruta('POST', '/proyectos/excedente', null, false, 'error.falta.item'),
            new Ruta('PUT', '/proyectos/excedente', null, false, 'error.falta.item'),
            new Ruta('DELETE', '/proyectos/excedente', null, false, 'error.falta.item'),
            new Ruta('GET', '/proyectos/{id}/asistencias', null, false, 'asistencias.listar'),
            new Ruta('POST', '/proyectos/{id}/asistencias', Permisos::AVANCE, false, 'asistencias.crear'),
            new Ruta('GET', '/proyectos/{id}/incidencias', null, false, 'incidencias.listar'),
            new Ruta('POST', '/proyectos/{id}/incidencias', Permisos::AVANCE, false, 'incidencias.crear'),
            new Ruta('GET', '/proyectos/{id}/materiales', null, false, 'materiales.proyecto.listar'),
            new Ruta('POST', '/proyectos/{id}/materiales', Permisos::GESTION_OBRA, false, 'materiales.proyecto.asignar'),
            new Ruta('GET', '/proyectos/{id}/documentos', null, false, 'documentos.listar'),
            new Ruta('POST', '/proyectos/{id}/documentos', Permisos::DOC, false, 'documentos.crear'),
            new Ruta('GET', '/proyectos/{id}/inactividades', null, false, 'inactividades.listar'),
            new Ruta('POST', '/proyectos/{id}/inactividades', Permisos::DOC, false, 'inactividades.crear'),
            new Ruta('GET', '/proyectos/{id}/excedentes', null, false, 'excedentes.listar'),
            new Ruta('POST', '/proyectos/{id}/excedentes', Permisos::DOC, false, 'excedentes.crear'),
            new Ruta('GET', '/proyectos/{id}/planificacion', null, false, 'planificacion.proyecto.obtener'),
            new Ruta('POST', '/proyectos/{id}/planificacion', Permisos::GESTION_OBRA, false, 'planificacion.proyecto.crear'),
            new Ruta('GET', '/proyectos', null, false, 'proyectos.listar'),
            new Ruta('POST', '/proyectos', Permisos::GESTION_OBRA, false, 'proyectos.crear'),
            new Ruta('GET', '/proyectos/{id}', null, false, 'proyectos.mostrar'),
            new Ruta('PUT', '/proyectos/{id}', Permisos::GESTION_OBRA, false, 'proyectos.editar'),
            new Ruta('DELETE', '/proyectos/{id}', Permisos::GESTION_OBRA, false, 'proyectos.eliminar'),
        ];
    }
}
